### ISSUE TITLE
AttributeError: 'CompositeField' object has no attribute 'meta'

### ISSUE THREAD

**Issue by xiaohk** [vita-epfl/openpifpaf#206]
Hello, I'm trying to run the [colab notebook](https://colab.research.google.com/drive/1H8T4ZE6wc0A9xJE4oGnhgHpUpAH5HL7W) but with version 0.11.1, but I got this following error. I didn't see this error when using openpifpaf 0.10.

```
net_cpu, _ = openpifpaf.network.factory(checkpoint='resnet101')
```

```
Downloading: "http://github.com/vita-epfl/openpifpaf-torchhub/releases/download/v0.10.0/resnet101block5-pif-paf-paf25-edge401-191012-132602-a2bf7ecd.pkl" to /root/.cache/torch/checkpoints/resnet101block5-pif-paf-paf25-edge401-191012-132602-a2bf7ecd.pkl
100%
175M/175M [00:02<00:00, 71.7MB/s]

/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'openpifpaf.network.nets.Shell' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'openpifpaf.network.basenetworks.BaseNetwork' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torchvision.models.resnet.Bottleneck' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'openpifpaf.network.heads.CompositeField' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-69da482468b8> in <module>()
----> 1 net_cpu, _ = openpifpaf.network.factory(checkpoint='resnet101')

2 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    592                 return modules[name]
    593         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 594             type(self).__name__, name))
    595 
    596     def __setattr__(self, name, value):

AttributeError: 'CompositeField' object has no attribute 'meta'
```

**Comment by svenkreiss** [comment]
The API and internal objects changed in version 0.11.
There is a new iPython notebook in docs: `docs/predict.ipynb` which is updated and continuously tested. I need to update Colab with that version.

**Comment by svenkreiss** [comment]
I have updated the link to a new Colab notebook that works with v0.11.
https://colab.research.google.com/drive/1KJN50tokGuatnO-jxlUIiQdJf4OPlZQ-?usp=sharing

**Comment by MoonBunnyZZZ** [comment]
> I have updated the link to a new Colab notebook that works with v0.11.
> https://colab.research.google.com/drive/1KJN50tokGuatnO-jxlUIiQdJf4OPlZQ-?usp=sharing

it still doesn't work now

**Comment by svenkreiss** [comment]
Only the pretrained models listed in the README are currently compatible. I hope to have pretrained ResNet models soon but it might take a while.

**Comment by svenkreiss** [comment]
pretrained resnet50 is now available in 0.11.2
